---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - helm-repository.yaml
  - helm-release.yaml
  - alertmanager-secret.sops.yaml
  - grafana-oidc-secret.sops.yaml
  - ingressroute.yaml
  - additional-scrape-configs.yaml
configMapGenerator:
  - name: kube-prometheus-stack-helm-values
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/managed-by: flux
